<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Library</OutputType>
		<IsPackable>false</IsPackable>

		<RootNamespace>NoP77svk.AspNetBrowserAutoLaunch.Tests</RootNamespace>
		<AssemblyName>NoP77svk.AspNetBrowserAutoLaunch.Tests</AssemblyName>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\IsExternalInit.cs" Link="IsExternalInit.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Update="$(ProjectDir)/*_Data/**/*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AspNetBrowserAutoLaunch.Core\AspNetBrowserAutoLaunch.Core.csproj" />
	</ItemGroup>

</Project>
