name: On-commit/push check (outside of release)

on:
  push:
    branches:
    - '**'
    ignore-tags:
    - '**'
  pull_request:
    branches:
    - main
    ignore-tags:
    - '**'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        dotnet-version: |
          10.0.x
          8.0.x
          6.0.x
    - name: Checkout
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      with:
        lfs: true
    - name: Configure private NuGet source credentials
      run: ./.github/ci/Configure-NuGetSource.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Solution clean
      run: |
        rm -rfv */bin */obj && rm -rfv */bin */obj
    - name: NuGet restore
      run: dotnet restore
    - name: Check for vulnerable packages
      run: ./.github/ci/Check-VulnerablePackages.sh
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build -- --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml
    - name: Enforce code coverage
      shell: pwsh
      run: ./.github/ci/Enforce-CodeCoverage.ps1
